language: haskell

before_install:
  - wget https://github.com/massysett/decnumber/releases/download/v368-3/libdecnumber-368-3.tar.gz
  - tar xf libdecnumber-368-3.tar.gz
  - cd libdecnumber-368-3
  - ./configure && make && sudo make install
  - sudo ldconfig
  - cd ..

# Install build dependencies
install:
  - cabal sdist --output-directory playpen
  - cd playpen
  - cabal install --only-dependencies


script:
  - cabal configure --enable-tests
  - cabal build
  - dist/build/tasty-test/tasty-test --quickcheck-max-size=100 --quickcheck-tests=10000
