before_install:
  - wget https://github.com/massysett/decnumber/releases/download/v368-3/libdecnumber-368-3.tar.gz
  - tar xf libdecnumber-368-3.tar.gz
  - cd libdecnumber-368-3
  - ./configure && make && sudo make install
  - sudo ldconfig
  - cd ..

install:
  - cabal configure --enable-tests
  - cabal install --only-dependencies
  - cabal build

script:
  - dist/build/tasty-test/tasty-test
