language: haskell

before_install:
  - wget https://github.com/massysett/decnumber/releases/download/v368-3/libdecnumber-368-3.tar.gz
  - tar xf libdecnumber-368-3.tar.gz
  - cd libdecnumber-368-3
  - ./configure && make && sudo make install
  - sudo ldconfig
  - cd ..

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=always
